### PR TITLE
Upgrade maven 3.8.1 + prototype for global lock

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gnodet** [comment]
@michael-o you may want to have a look at this sync context implementation.  It has the benefits of being global to the host without requiring any kind of setup from the user.

**Comment by michael-o** [comment]
Thanks, will take a deep look when we complete 1.7.0 with @cstamas. Hope this will happen until next week.

**Comment by gnodet** [comment]
Draft PR at https://github.com/apache/maven-resolver/pull/105

**Comment by githubbot-eric** [comment]
@gnodet 

Our Jenkins work builders are actually K8s pod based.
I don't think this solution can benefit the container based Jenkins solution.

**Pull request merged**
