### PR TITLE
Implement build cancelation

### LINKED ISSUE #127: Implement build cancellation
Some support is already provided (such as a specific state and such) but we need to intercept the Ctrl+C / interrupt event, send a cancellation request and check on the daemon side.

### PR DESCRIPTION
**Pull request by ppalaga**
fixes #127

### CODE REVIEW

**Comment by ppalaga** [comment]
This is a bit different than the original https://github.com/mvndaemon/mvnd/pull/195 : the cancellation request is not enforced while the DaemonConnector is connecting. It is rather stored in a temporary outbound queue, waiting for the connection and is send to the daemon only after when the connection is established. Could you please review @gnodet ?

**Comment by gnodet** [comment]
I'd like to keep the ability to cancel the client during the first few seconds while it's trying to connect to a daemon.
I think it currently somewhat works because of https://github.com/mvndaemon/mvnd/issues/193, so I think the daemon is killed very early when hitting `Ctrl+C`.

Also, it seems the client is waiting for the daemon to process the cancellation request cleanly.  I don't think this is a desirable behaviour.  It can slow the response on the client side a few seconds.  The client should send the cancel message and exit early.

**Comment by gnodet** [comment]
> I'd like to keep the ability to cancel the client during the first few seconds while it's trying to connect to a daemon.
> I think it currently somewhat works because of #193, so I think the daemon is killed very early when hitting `Ctrl+C`.
> 
> Also, it seems the client is waiting for the daemon to process the cancellation request cleanly. I don't think this is a desirable behaviour. It can slow the response on the client side a few seconds. The client should send the cancel message and exit early.

I should have a proposal in a few minutes...

**Comment by gnodet** [comment]
@ppalaga see https://github.com/gnodet/mvnd/commit/3a38265fac9bb8ce1695b84f5f3f90c770d4d7db

**Comment by ppalaga** [comment]
Thanks, amended with minor changes in c52dfa3

**Pull request merged**
