### PR TITLE
Make sure the environment is properly updated, fixes #352

### LINKED ISSUE #352: Make sure the environment is properly updated
The current dir and environment variables should be set to the ones of the client, see #125 #234.
This will require 2 native methods from jansi to access the stdlib `chdir` and `setenv` functions.

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by ppalaga** [comment]
These changes introduce potential incompatibilities with existing or future JVM vendors/versions we currently do not test with. The same holds for other operating systems on which we currently do not test. 
Is there any known problem except for #234 why we need this? Is #234 serious enough to justify a fix as risky as this one?

**Comment by gnodet** [comment]
> These changes introduce potential incompatibilities with existing or future JVM vendors/versions we currently do not test with. The same holds for other operating systems on which we currently do not test.
> Is there any known problem except for #234 why we need this? Is #234 serious enough to justify a fix as risky as this one?

I think the fact that the current directory is not updated is serious enough problem, see the integration test which clearly demonstrates this fact.
We can always fix future incompatibles if needed, and if any error occurs, the code falls back to the previous behaviour, i.e. warning the user of the mismatch.  Fwiw, gradle does the same kind of trick.

**Comment by gnodet** [comment]
The build obviously fail until a release with https://github.com/fusesource/jansi/commit/6d61a763ebc4a97399e57c38e7c2e0eac7b8cf3c is provided.

**Comment by ppalaga** [comment]
> gradle does the same kind of trick.

That resolved all my concerns :D

**Review by ppalaga — APPROVED** [review]

**Comment by gnodet** [comment]
Merged

**Pull request closed without merging**
