### PR TITLE
Add jansi native libraries

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by gnodet — COMMENTED** [review]
I'm not really convinced by this commit, since we loose the fact that projects are identified by the `projectGA` output.

**Comment by ppalaga** [comment]
> we loose the fact that projects are identified by the `projectGA` output.

You mean the logging changes in SmartBuilderImpl? https://github.com/mvndaemon/mvnd/pull/117/commits/bd69997eb4f3c87ca62db642a69c112711db5a60

The log messages stay the same. The rationale is that the `projectGA(project)` method does not need to be called if the log level is lower than debug.

For the jansi native libraries commit, I am not 100% sure this is the right approach. In stock Maven the jansi native libs are in `lib/jansi-native/*` and they are not in jars. We do not include those in our distro and I think we should not as long as we use a different jansi version: 1.17.1 on stock maven vs. 1.8 on our side. Do you have any opinion on that?

The CI failure on Linux is intermittent https://github.com/mvndaemon/mvnd/issues/102
The failure on Mac seems to be real - would you mind having a look?

**Comment by ppalaga** [comment]
I have moved the logging change into a separate PR: https://github.com/mvndaemon/mvnd/pull/134

**Comment by gnodet** [comment]
> > we loose the fact that projects are identified by the `projectGA` output.
> 
> You mean the logging changes in SmartBuilderImpl? [bd69997](https://github.com/mvndaemon/mvnd/commit/bd69997eb4f3c87ca62db642a69c112711db5a60)
> 
> The log messages stay the same. The rationale is that the `projectGA(project)` method does not need to be called if the log level is lower than debug.
> 
> For the jansi native libraries commit, I am not 100% sure this is the right approach. In stock Maven the jansi native libs are in `lib/jansi-native/*` and they are not in jars. We do not include those in our distro and I think we should not as long as we use a different jansi version: 1.17.1 on stock maven vs. 1.8 on our side. Do you have any opinion on that?

AFAIK, the main problem is that Jansi does not work when running the natively compiled mvnd.  I don't really care if the native libraries are extracted in the distribution or embedded at the moment.
I'm actively working on Jansi to support missing architectures and fixing windows problems.

> 
> The CI failure on Linux is intermittent #102
> The failure on Mac seems to be real - would you mind having a look?

**Comment by ppalaga** [comment]
> AFAIK, the main problem is that Jansi does not work when running the natively compiled mvnd. I don't really care if the native libraries are extracted in the distribution or embedded at the moment.
> I'm actively working on Jansi to support missing architectures and fixing windows problems.

OK, let's close this then

**Pull request closed without merging**
