### PR TITLE
Fix concurrent access to local repository

### LINKED ISSUE #14: Concurrent access to the local repository
Creating this issue to discuss the strategy, because this will hit us sooner or later. It looks like the stock Maven still does not synchronize the access to the local repo. Due to this, two threads or processes can write into the same file which may result in a corrupted data.

https://issues.apache.org/jira/browse/MNG-2802 https://github.com/takari/takari-local-repository

### PR DESCRIPTION
**Pull request by lanmaoxinqing**
remove takari , upgrade maven-resolver version to 1.6.1, try to resolve  #14 #281

### CODE REVIEW

**Comment by lanmaoxinqing** [comment]
I ignored the maven-resolver v1.4.1 unzipped from maven-core and copy v1.6.1 into /lib/ext.
It is a pain point that newer maven-resolver versions will no longer automatic upgrade through maven-core.
Any nicer ideas?

**Comment by gnodet** [comment]
> It is a pain point that newer maven-resolver versions will no longer automatic upgrade through maven-core.
> Any nicer ideas?

What do you mean ? I don't understand...

**Comment by lanmaoxinqing** [comment]
> 
> What do you mean ? I don't understand...

Sorry for my poor english... I excludes `maven-resolver*` unzipped from maven-core in `maven-distro.xml`
```xml
    <artifactSet to="/mvn">
        <artifact id="org.apache.maven:apache-maven:tar.gz:bin">
            <unpack useRoot="false"
                    excludes="...lib/maven-resolver-api*,lib/maven-resolver-impl*,lib/maven-resolver-util*,lib/maven-resolver-spi*"/>
        </artifact>
    </artifactSet>
```
and copy v1.6.1 to /mvn/lib/ext
image

so even we upgrade maven which uses higher version of `resolver`, it still will be v1.6.1

**Comment by gnodet** [comment]
I understand now.
I think this PR is obsolete with #393 which includes the resolver 1.6.2 release.
However, I need to check that the takari one is actually not included and that we're actually using the new locking mechanism.

**Comment by gnodet** [comment]
> I understand now.
> I think this PR is obsolete with #393 which includes the resolver 1.6.2 release.
> However, I need to check that the takari one is actually not included and that we're actually using the new locking mechanism.

So upgrading to the new 1.6.2 maven resolver is not sufficient, as the default locking mechanism is just to not lock anything.  There are two implementations: one that only works for in-JVM locking (so between threads), and another one that need a Redis server to run.  So there's currently out-of-the-box option for mvnd.
I'll see if I can write a small dedicated client/server that could be launched by the client if not already started and used by all daemons.

**Comment by lanmaoxinqing** [comment]
> So upgrading to the new 1.6.2 maven resolver is not sufficient, as the default locking mechanism is just to not lock anything. There are two other implementations: one that only works for in-JVM locking (so between threads), and another one that need a Redis server to run. So there's currently out-of-the-box option for mvnd.
> I'll see if I can write a small dedicated client/server that could be launched by the client if not already started and used by all daemons.

You are right, `DefaultSyncContextFactory` in resolver 1.6.2 uses  empty implementation, this PR don't really fix #281 . I'll gonna close it.

**Pull request closed without merging**
